### ISSUE TITLE
Code blocks break page width on mobile

### ISSUE THREAD

**Issue by thiemo** [yinkakun/eleventy-duo#4]
On pages displaying markdown code blocks containing very long lines of code this will lead to the entire page width getting much wider than the viewport on mobile. Meaning: Not only the code block is scrolling horizontally, but also the entire page.

Example (view on mobile): https://nifty-shirley-6ebc16.netlify.app/posts/yet-another-post-with-code-samples/

**Comment by yinkakun** [comment]
Thanks for letting me know.
I fixed that by restricting the `pre` tag to a max width of 100vh.
Issue should be fixed now.
