### ISSUE TITLE
Feature request: minify html and js

### ISSUE THREAD

**Issue by teamcrisis** [yinkakun/eleventy-duo#5]
I'm new to 11ty and webpack.

Am I missing it? Is there not a way to minify HTML and JS? 

I see css minify is provided. Any chance you'd be willing to add html and js support?

**Comment by yinkakun** [comment]
HTML Minification is now added and it's triggered only on production build, that is when you run `yarn build`

**Comment by teamcrisis** [comment]
Thank you!
