### ISSUE TITLE
TemplateContentRenderError for sitemap

### ISSUE THREAD

**Issue by teamcrisis** [yinkakun/eleventy-duo#6]
When I add this to a post:

```
---
date: '2020-12-28'
updated: '2021-02-12'
---
```

I get the following error:

```
`TemplateContentRenderError` was thrown
> (./src/sitemap.njk) [Line 8, Column 51]
  Error: Unable to call `item["data"]["updated"]["toISOString"]`, which is undefined or falsey
```

Seems `updated` is causing the issue, but what is wrong with it?

**Comment by teamcrisis** [comment]
I'm new to 11ty, so no idea if this is the correct way to handle this, but here is a possible work around.

In `sitemap.njk` update to `<lastmod>{{ item.data.updated | dateToIso }}</lastmod>`

in `.eleventy.js` add a filter

```
 eleventyConfig.addFilter('dateToIso', (dateObj) => {
    var str = dateObj;
    darr = str.split("-");
    var dobj = new Date(parseInt(darr[0]),parseInt(darr[1])-1,parseInt(darr[2]));
    return dobj.toISOString();
  });
```

**Comment by yinkakun** [comment]
Thanks so much for the heads up.

Indeed, the error is triggered by adding `updated` to the frontmatter - I don't have any useful explanation for that now 🙈.
Your suggested solution fixed it, I just modified it a little bit to use regular Javascript date functionality

```js
  eleventyConfig.addFilter('dateToIso', (dateString) => {
    return new Date(dateString).toISOString()
  });
```

It's fixed now, thanks so much.

**Comment by teamcrisis** [comment]
Thanks for this. 

Just an FYI, the same thing will need to be done in your `else` statement if setting the `date` in frontmatter as well.

**Comment by yinkakun** [comment]
> Thanks for this.
> 
> Just an FYI, the same thing will need to be done in your `else` statement if setting the `date` in frontmatter as well.

Yeah, did that.
