### ISSUE TITLE
Assistance in personal project

### ISSUE THREAD

**Issue by talmax1124** [yinkakun/eleventy-duo#9]
Hello, Quick question. Is there a way that you could help me implement tags and that navigation thing in my repository? I tried and have failed tremendously. Could you do a pull request or could we do a live share? @yinkakun 

https://github.com/talmax1124/knighttimesnews-restore

**Comment by yinkakun** [comment]
Hello @talmax1124 
Apologies for the late response (I had it in my mind then forgot about it), I hope you've fixed the issue, or do you still need my assistance?

**Comment by yinkakun** [comment]
On it sirrr.
